name: build-solution

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore NuGet Packages
        working-directory: src
        run: nuget restore AasxPackageExplorer.sln

      - name: MSBuild
        working-directory: src
        run: |
          msbuild
            AasxPackageExplorer.sln
            -t:build
            /p:PackageLocation="packages"
