name: Build-test-inspect-workflow

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, edited]

  push:
    branches:
      - master
      - MIHO/JoinMMV3RC02andDynMen_FQ1_Q1

jobs:
  Build-test-inspect:
    runs-on: windows-latest
    if: contains(github.event.pull_request.body, 'The workflow build-test-inspect was intentionally skipped.') == false
    steps:
      - uses: actions/checkout@master

      - name: Display repository name
        env:
          REPOSITORY: ${{ github.repository }}
        run: |
          Write-Host "The repository is: ${env:REPOSITORY}"

      - name: Install .NET core 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install tools for build-test-inspect
        working-directory: src
        run: powershell .\InstallToolsForBuildTestInspect.ps1

      - name: Install build dependencies
        working-directory: src
        run: powershell .\InstallBuildDependencies.ps1

#      - name: Install coveralls.net (to send test coverage)
#        working-directory: src
#        if: github.repository == 'admin-shell-io/aasx-package-explorer'
#        run: dotnet tool install coveralls.net --version 2.0.0-beta0002

#      - name: Build
#        working-directory: src
#        run: powershell .\BuildForDebug.ps1

      - name: Check that all Doctests are there
        working-directory: src
        run: powershell .\Doctest.ps1 -check

#      - name: Download samples
#        working-directory: src
#        run: powershell .\DownloadSamples.ps1

#      - name: Test
#        working-directory: src
#        run: powershell .\Test.ps1

#      - name: Send to Coveralls
#        working-directory: src
#        env:
#          HEAD_REF: ${{ github.head_ref }}
#          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
#        run: |
#          # At the moment we only run coveralls on master.
#          # However, we leave this legacy logic here in case we introduce
#          # new branching policy or new coverage publishing rules.
#          if (${env:GITHUB_REF}.StartsWith("refs/pull/"))
#          {
#            $branch = ${env:HEAD_REF} -Replace 'refs/heads/', ''
#          }
#          else
#          {
#            $branch = ${env:GITHUB_REF} -Replace 'refs/heads/', ''
#          }
#
#          $commit = $env:GITHUB_SHA
#
#          echo "Branch is: $branch"
#          echo "Commit is: $commit"
#          dotnet tool run csmacnz.Coveralls --opencover -i ..\artefacts\CoverageResults.xml --useRelativePaths --repoToken $env:COVERALLS_REPO_TOKEN --commitId $commit --commitBranch $branch

      - name: Inspect code with Build
        working-directory: src
        run: powershell .\InspectCode.ps1

      - name: Upload Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: resharper-code-inspection.xml
          path: ./artefacts/resharper-code-inspection.xml
