name: Check-release-workflow

on:
  pull_request:
    branches:
      - master
      - MIHO/*V3*
    types: [opened, synchronize, reopened, edited]

  push:
    branches:
      - master
      - MIHO/*V3*

jobs:
  Check-release:
    runs-on: windows-latest
    if: contains(github.event.pull_request.body, 'The workflow check-release was intentionally skipped.') == false
    steps:
      - uses: actions/checkout@master

      - name: Set timestamp
        id: setTimestamp
        run: |
          $timestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH-mm-ssZ")
          Write-Output "::set-output name=timestamp::$timestamp"

      - name: Install .NET core 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install build dependencies
        working-directory: src
        run: powershell .\InstallBuildDependencies.ps1

      - name: Build for release
        working-directory: src
        run: powershell .\BuildForRelease.ps1

      - name: Package
        working-directory: src
        run: powershell .\PackageRelease.ps1 -version LATEST.alpha

      - name: Upload latest
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: aasx-package-explorer.LATEST.alpha.${{ steps.setTimestamp.outputs.timestamp }}
          path: artefacts/release/LATEST.alpha/aasx-package-explorer.zip

      - name: Upload latest small
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: aasx-package-explorer-small.LATEST.alpha.${{ steps.setTimestamp.outputs.timestamp }}
          path: artefacts/release/LATEST.alpha/aasx-package-explorer-small.zip

      - name: Upload latest small
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: aasx-package-explorer-small.LATEST.alpha.${{ steps.setTimestamp.outputs.timestamp }}
          path: artefacts/release/LATEST.alpha/aasx-package-explorer-small.zip

      - name: Upload latest BlazorUI
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: aasx-package-explorer-blazorexplorer.LATEST.alpha.${{ steps.setTimestamp.outputs.timestamp }}
          path: artefacts/release/LATEST.alpha/aasx-package-explorer-blazorexplorer.zip